<?php

namespace ContainerJjt5upR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRateJokeControllerService extends App_KernelProdContainer
{
    /*
     * Gets the public 'App\Controller\RateJokeController' shared autowired service.
     *
     * @return \App\Controller\RateJokeController
     */
    public static function do($container, $lazyLoad = true)
    {
        $container->services['App\\Controller\\RateJokeController'] = $instance = new \App\Controller\RateJokeController();

        $instance->setContainer(($container->privates['.service_locator.l1ae.Qz'] ?? $container->load('get_ServiceLocator_L1ae_QzService'))->withContext('App\\Controller\\RateJokeController', $container));

        return $instance;
    }
}
