<?php

namespace ContainerJjt5upR;


use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRatingsRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RatingsRepository' shared autowired service.
     *
     * @return \App\Repository\RatingsRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RatingsRepository'] = new \App\Repository\RatingsRepository(($container->services['doctrine'] ?? $container->getDoctrineService()));
    }
}
