<?php

namespace ContainerQAkjxie;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_SjE1ZHService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.sjE1Z_h' shared service.
     *
     * @return \App\Entity\JokesRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ViewJokeController::index()": the $jokesRepository argument is type-hinted with the non-existent class or interface: "App\\Entity\\JokesRepository".');
    }
}
