<?php

namespace ContainerQAkjxie;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_T_2usMService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.T.2usM_' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.T.2usM_'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService, [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'jokesRepository' => ['privates', '.errored.sjE1Z_h', NULL, 'Cannot determine controller argument for "App\\Controller\\ViewJokeController::index()": the $jokesRepository argument is type-hinted with the non-existent class or interface: "App\\Entity\\JokesRepository".'],
        ], [
            'doctrine' => '?',
            'jokesRepository' => '?',
        ]);
    }
}
