<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJjt5upR\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJjt5upR/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerJjt5upR.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerJjt5upR\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerJjt5upR\App_KernelProdContainer([
    'container.build_hash' => 'Jjt5upR',
    'container.build_id' => '6beda619',
    'container.build_time' => 1648253556,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJjt5upR');
