<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQVxqY47\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQVxqY47/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerQVxqY47.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerQVxqY47\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerQVxqY47\App_KernelDevDebugContainer([
    'container.build_hash' => 'QVxqY47',
    'container.build_id' => '9a9a89a0',
    'container.build_time' => 1648253486,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQVxqY47');
