<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXBmGSch\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXBmGSch/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXBmGSch.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXBmGSch\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXBmGSch\App_KernelDevDebugContainer([
    'container.build_hash' => 'XBmGSch',
    'container.build_id' => 'd2e83d7c',
    'container.build_time' => 1647882942,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXBmGSch');
